tests: refactor systests into separate modules w/ pytest fixtures
googleapis/python-bigtable pull request #393
Opened 2021-07-22 16:04 UTC by tseaver

Closes #391.

2021-07-22 18:14 UTC, tseaver commented
Flaky sample error reported as #394.

2021-07-23 20:34 UTC, tseaver commented
#394 strikes again.  I'll retry here after getting #395 merged.

2021-09-15 17:11 UTC, chrisrossi requested changes

2021-09-15 18:03 UTC, tseaver commented on tests/system/test_data_api.py
> +COLUMN_FAMILY_ID1 = "col-fam-id1"
It is an oddity of the back-end that row keys, column names, and cell values must be bytes (at the protobuf level), while column family IDs are strings.

2021-09-15 18:03 UTC, tseaver commented on tests/system/test_data_api.py
> +    row_data.consume_all()
The test is added in https://github.com/googleapis/google-cloud-python/pull/5002.  It feels like a "smoke test" for the expectation that timestamps passed in as filters get rounded down / up to the nearest millisecond (the back-end would barf when passed microsecond values (https://github.com/googleapis/google-cloud-python/issues/4932).

2021-09-15 18:21 UTC, tseaver commented on tests/system/conftest.py
> +    if not in_emulator:
54bf4c1

2021-09-15 18:21 UTC, tseaver commented on tests/system/conftest.py
> +    if not in_emulator:
54bf4c1

2021-09-15 18:22 UTC, tseaver commented on tests/system/test_data_api.py
> +    for row in data_table.read_rows():
That test was originally added in https://github.com/googleapis/google-cloud-python/pull/5360:  I just ported it.

Assuming we don't have race conditions with other CI runs, I would expect there to be no rows in the table after a call to `truncate`.  4b11ce8 changes the assertion accordingly.

2021-09-15 18:22 UTC, tseaver commented on tests/system/test_data_api.py
> +    for row_key in row_keys:
bec068c

2021-09-15 18:51 UTC, chrisrossi approved these changes
LGTM, thanks!

2021-09-15 19:02 UTC, merged