chore: optimize row merging
googleapis/python-bigtable pull request #628
Opened 2022-08-08 20:33 UTC by igorbernstein2

This PR rewrites the row merging logic to be more correct and improve performance:
- extract row merging logic into its own class to simplify complexity of ReadRows handling
- Use OrderedDict instead of dict() for `{family: { qualifier: [] }}` data, this should maintain serverside ordering (family in creation order and qualifier in lexiographical). 
- define an explicit state machine with states implemented as methods
- add various optimizations like:
  - __slots__ on hot objects to avoid dict lookups
  - avoiding dict lookups for contiguous family and qualifier keys
 
Overall this improves performance by 20% and in my opinion is a lot more readable

2022-08-08 20:56 UTC, mutianf commented on google/cloud/bigtable/row_merger.py
> +            self.row.cell.value = bytearray()
how will we add the current chunk to the cell value? should we add self.row.cell.value += chunk.value to line 406?

2022-08-09 20:20 UTC, mutianf requested changes

2022-08-09 20:20 UTC, mutianf commented on google/cloud/bigtable/row_merger.py
> +        if chunk.HasField("family_name"):
Can we simplify this to:

if !chunk.HasField("family_name") or !chunk.HasField("qualifier"):
  raise InvalidChunk("missing family_name or qualifier for a new cell")

?

2022-08-09 20:20 UTC, mutianf commented on google/cloud/bigtable/row_merger.py
> +            raise InvalidChunk("missing family for a new cell")
```suggestion
            raise InvalidChunk("missing qualifier for a new cell")
```

2022-08-09 20:20 UTC, mutianf commented on google/cloud/bigtable/row_merger.py
> +        if chunk.HasField("family_name"):
And should we move this check before we create a new PartialCell?

2022-08-09 20:20 UTC, mutianf commented on google/cloud/bigtable/row_merger.py
> +        if chunk.value_size > 0:
what's chunk.value_size? Is it the remaining size of this cell?

2022-08-09 20:20 UTC, mutianf commented on google/cloud/bigtable/row_data.py
> +            # could've updated last_scanned_row_key
why would it be updated? Isn't last_seen_row_key only updated in handleRowComplete?

2022-08-10 14:25 UTC, mutianf commented on google/cloud/bigtable/row_merger.py
> +        if chunk.HasField("family_name"):
Add a comment to explain the family and qualifier buffer

2022-08-10 20:08 UTC, mutianf approved these changes

2022-08-11 18:11 UTC, Mariatta commented
Can you add the documentation of row_merger to the Sphinx documentation?
First create `docs/row-merger.rst` (see the example content from `row-data.rst`)

Then add `row-merger` to the `usage.rst` line 18.

We should also update the usages of row_data.Cell / row_data.PartialRowData / row_data.InvalidChunk in the documentation to use the row_merger instead.

2022-08-12 16:07 UTC, dbolduc approved these changes
The row merging logic LGTM. I left some nits that you can fix or not.

2022-08-12 16:07 UTC, dbolduc commented on google/cloud/bigtable/row_merger.py
> +        if self.row.cell.value_index > 0:
can we drop `value_index` from `PartialCell` and just check for:
```py
if self.row.cell.value:
```

2022-08-17 18:07 UTC, igorbernstein2 commented on google/cloud/bigtable/row_merger.py
> +        if chunk.value_size > 0:
yea, I wanted to keep explicit

2022-08-17 18:07 UTC, igorbernstein2 commented on google/cloud/bigtable/row_merger.py
> +    ROW_COMPLETE = "COMPLETE_ROW"
yep, thanks!

2022-08-17 18:08 UTC, igorbernstein2 commented on google/cloud/bigtable/row_merger.py
> +        The internal state of this class will maintain state across multiple
done

2022-08-17 18:08 UTC, igorbernstein2 commented on google/cloud/bigtable/row_merger.py
> +    There can be multiple state transitions for each chunk, ie. a single chunk
done

2022-08-17 19:17 UTC, Mariatta approved these changes

2022-08-17 20:04 UTC, merged