[DRAFT] feat: read_rows helpers
googleapis/python-bigtable pull request #778
Opened 2023-05-18 19:01 UTC by daniel-sanche

blocked on [read_rows PR](https://github.com/googleapis/python-bigtable/pull/762). Diff currently includes changes from that branch. Do not review until read_rows is merged

This PR adds two useful helper functions:
- `row_exists`: returns a bool indicating whether the row was found on the backend, without overhead of actually fetching its data
- `read_row`: returns an individual row from the backend, or raises `RowNotFound` if it doesn't exist

2023-06-14 20:49 UTC, daniel-sanche commented on google/cloud/bigtable/client.py
> +            - google.cloud.bigtable.exceptions.RowNotFound: if the row does not exist
Yeah sure, I changed the signature to `Row | None` and made the change

2023-06-14 20:49 UTC, daniel-sanche commented on google/cloud/bigtable/client.py
> +            raise ValueError("row_key must be string or bytes")
Yeah sure, that's easy enough to pass through. Added

2023-06-16 18:16 UTC, mutianf approved these changes

2023-06-16 18:24 UTC, mutianf requested changes
please add the retry wrapper for read_row

2023-06-16 19:02 UTC, mutianf approved these changes

2023-06-16 19:18 UTC, merged